### ISSUE TITLE
VLAN設定が空のirbを削除する

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#23]
支線VLANを削除した際、coreのirb IFが残っているとVLAN設定が空となるため、ansibleにて処理エラーとなる。
対処方法として以下が考えられる。

- nbckにて、VLAN設定が空のirb IFを削除
- ansibleにて、例外処理を追加（WARNINGを出してスキップ）

**Comment by kitaguch** [comment]
前者のnbckで不整合を正す方針としたい。

**Comment by mi2428** [comment]
> ansibleにて、例外処理を追加（WARNINGを出してスキップ）
想像しているようなWARNINGを出すのは無理です。なので前者一択

**Comment by mi2428** [comment]
要するに
- NBのirb.XXXでVLAN設定が入っていない場合は，nbckでインターフェイスirb.XXXを削除する

**Comment by mi2428** [comment]
こうなる

```
[WARNING]:  * Failed to parse /home/titanoc/tn4-player/inventories/production/netbox.py with script plugin: Inventory script (/home/titanoc/tn4-player/inventories/production/netbox.py) had an execution error:
Traceback (most recent call last):   File "/home/titanoc/tn4-player/inventories/production/netbox.py", line 632, in <module>     inventory = dynamic_inventory()   File
"/home/titanoc/tn4-player/inventories/production/netbox.py", line 615, in dynamic_inventory     "vlans":          cf.get_device_vlans(hostname),   File "/home/titanoc/tn4-player/inventories/production/netbox.py", line
561, in get_device_vlans     vlans.extend(self.get_vlans("core-honkan"))   File "/home/titanoc/tn4-player/inventories/production/netbox.py", line 244, in get_vlans     irb_vids.add(vlan["vid"]) TypeError: 'NoneType'
object is not subscriptable
[WARNING]:  * Failed to parse /home/titanoc/tn4-player/inventories/production/netbox.py with ini plugin: /home/titanoc/tn4-player/inventories/production/netbox.py:4: Expected key=value host variable assignment, got:
pprint
[WARNING]: Unable to parse /home/titanoc/tn4-player/inventories/production/netbox.py as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
```

**Comment by kitaguch** [comment]
「NBのirb.XXXでVLAN設定が入っていない場合は，nbckでインターフェイスirb.XXXを削除する」
この実装をお願いします。

**Comment by mi2428** [comment]
実装した気持ち。クローズ

- VLANが空っぽなインターフェイスはInterface ModeがNoneに修正
- Interface ModeがNoneなirbインターフェイスはNBから削除

をそれぞれ独立したルールとして実装したので、**状況によっては nbck を2回連続で動かしてようやく綺麗になるかもしれない。** LaTeXのコンパイルと似たような理屈（latexmkは自動で2回実行してくれるけどnbckは手動で2回やらないといけない、いまのところ）
