### ISSUE TITLE
nbckのviolation出力がうまくない

### ISSUE THREAD

**Issue by mi2428** [yamaoka-kitaguchi-lab/tn4-player#7]
- Maser/Slaveで問題あるだけなのにEdge/Coreも無問題として出力される（変更差分のないviolation報告）
- core-honkan ae110

**Comment by kitaguch** [comment]
Edge/Core で変更がなくても、Master/Slave で変更があると出力されるみたいです。なので修正いらないものかも。

**Comment by mi2428** [comment]
これが直らないと #11 できない

**Comment by mi2428** [comment]
global desired と current を比較してるのが原因。local desired と current を比較すればいい

**Comment by mi2428** [comment]
while handling the above exception, another exception occurred. になってしまった

```
Traceback (most recent call last):
  File "/work/tn4-player/./bin/nbck", line 514, in <module>
    main()
  File "/home/shizk/.local/share/virtualenvs/tn4-player-ifwoWHZW/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/shizk/.local/share/virtualenvs/tn4-player-ifwoWHZW/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/shizk/.local/share/virtualenvs/tn4-player-ifwoWHZW/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shizk/.local/share/virtualenvs/tn4-player-ifwoWHZW/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/tn4-player/./bin/nbck", line 471, in main
    nbck.full_check(alt_table_bg=flg_alt_table_bg, verbose=flg_verbose)
  File "/work/tn4-player/./bin/nbck", line 156, in full_check
    self.__check_master_slave_tag_consistency()
  File "/work/tn4-player/./bin/nbck", line 444, in __check_master_slave_tag_consistency
    self.consistencies[dev_name][int_name]["desired"] = copy.deepcopy(desired_s_master[int_name])
```

**Comment by mi2428** [comment]
Master-Sに対してSlave-Oを貼ってたので落ちた。エラーハンドリングを追加して，警告表示後スキップするようにした

**Comment by mi2428** [comment]
新実装で解消されたことを祈る。よくわからないのでクローズ
