### ISSUE TITLE
nbckでURL指定が機能しない

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#8]
URL 指定しての nbck がうまくいかない

titanoc@ansible:~/tn4-player/netbox$ nbck -dv http://netbox.m.noc.titech.ac.jp:8000/ 0123456789technicaluser789abcdef01234567
2022-04-25T18:36:20 NBCK - NetBox Consistency Check
                    NetBox URL: http://netbox.m.noc.titech.ac.jp:8000/
Traceback (most recent call last):
  File "/home/titanoc/tn4-player/bin/nbck", line 516, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/titanoc/tn4-player/bin/nbck", line 471, in main
    nbck.load_inventories(verbose=flg_verbose)
  File "/home/titanoc/tn4-player/bin/nbck", line 82, in load_inventories
    self.nb.get_all_sites()
  File "/home/titanoc/tn4-player/bin/../netbox/netbox.py", line 120, in get_all_sites
    all_sites = self.query("/dcim/sites/")
  File "/home/titanoc/tn4-player/bin/../netbox/netbox.py", line 113, in query
    responses += res["results"]
KeyError: 'results'

未指定ではうまくいく：
titanoc@ansible:/home/kitaguchi$ nbck -dv
2022-04-26T08:32:10 NBCK - NetBox Consistency Check
                    NetBox URL: http://netbox.m.noc.titech.ac.jp:8000/
                    Fetched all Sites (88 sites fetched)
2022-04-26T08:32:12 Fetched all VLANs (605 VLANs fetched)
2022-04-26T08:32:13 Fetched all IP Addresses (194 addresses fetched)
2022-04-26T08:32:14 Fetched all Devices (162 devices fetched)
...

**Comment by mi2428** [comment]
トークン不正が原因，勘違いだったのでひとまずクローズ。
todo: netbox.py にトークン不正時の例外処理を追加する
